// OCADAX.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(OCADAX.tlb)，该类型库将成为
// OCADAX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(07615D63-5B5B-4750-9985-DCCCF921AA54), version(1.0),
  control ]
library OCADAXLib
{
	importlib(STDOLE_TLB);

	//  COCADAXCtrl 的主调度接口
	[ 
		uuid(D954DB96-FD53-4725-B012-746C5C163A6A)	
	]
	dispinterface _DOCADAX
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(1)] VARIANT_BOOL OpenFile(BSTR pathName);
	};

	//  COCADAXCtrl 的事件调度接口

	[ 
		uuid(E3968884-1FA8-4C6A-A939-C3598972E6C1)	
	]
	dispinterface _DOCADAXEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  COCADAXCtrl 的类信息
	[
		uuid(F73A286B-4E03-4DD8-A991-4A1321BD948B)
	]
	coclass OCADAX
	{
		[default] dispinterface _DOCADAX;
		[default, source] dispinterface _DOCADAXEvents;
	};

};
